services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # volumes:
    #   - .:/hackathon-backend
    depends_on:
      - db
      - cache
  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    # volumes:
    #   - .:/hackathon-db
  cache:
    # https://geshan.com.np/blog/2022/01/redis-docker/
    image: redis:7.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
