"""Configure score and metrics tables

Revision ID: 23711aedbb11
Revises: eb1ffeca18e5
Create Date: 2025-06-24 16:21:27.226229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23711aedbb11'
down_revision: Union[str, None] = 'eb1ffeca18e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('selectable_submission_count', sa.Integer(), nullable=True))
    op.add_column('competitions', sa.Column('daily_submission_limit', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('extra_submission_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'extra_submission_count')
    op.drop_column('competitions', 'daily_submission_limit')
    op.drop_column('competitions', 'selectable_submission_count')
    # ### end Alembic commands ###
