"""Add templates and commands

Revision ID: 2a78b28fd4d9
Revises: bc7a23024fbf
Create Date: 2025-03-09 11:04:27.291441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a78b28fd4d9'
down_revision: Union[str, None] = 'bc7a23024fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SENDER_REPO', 'ALL_REPOS', name='commandargtype').create(op.get_bind())
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('arg_type', postgresql.ENUM('SENDER_REPO', 'ALL_REPOS', name='commandargtype', create_type=False), nullable=False),
    sa.Column('allocated_ram', sa.Integer(), nullable=False),
    sa.Column('allocated_v_ram', sa.Integer(), nullable=False),
    sa.Column('allocated_cpu', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_foreign_key(None, 'teams', 'competitions', ['competition_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_table('commands')
    op.drop_table('templates')
    sa.Enum('SENDER_REPO', 'ALL_REPOS', name='commandargtype').drop(op.get_bind())
    # ### end Alembic commands ###
