"""Add score table

Revision ID: eb1ffeca18e5
Revises: b5575477e824
Create Date: 2025-06-23 21:32:18.901611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb1ffeca18e5'
down_revision: Union[str, None] = 'b5575477e824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ON_SUBMISSION', 'ON_COMPETITION_END', 'OTHER', name='runcommandtype').create(op.get_bind())
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score_metric_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('run_command_type', postgresql.ENUM('ON_SUBMISSION', 'ON_COMPETITION_END', 'OTHER', name='runcommandtype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['score_metric_id'], ['score_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('releases', 'score')
    op.drop_column('score_metrics', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_metrics', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('scores')
    sa.Enum('ON_SUBMISSION', 'ON_COMPETITION_END', 'OTHER', name='runcommandtype').drop(op.get_bind())
    # ### end Alembic commands ###
