services:
  sandbox:
    build:
      context: ..
      dockerfile: ./sandbox/Dockerfile
      args:
        TEMPLATE_NAME: "template"
        COMMAND_NAME: "command"
        ARGS: "repo1,repo2..."
    volumes:
      - ./sandbox/results:/sandbox/results # Bind the results directory to the sandbox container
